## Array Biçimlendirme işlemleri

**ndim:** boyut sayısı
<br>**shape:** boyut bilgisi
<br>**size:** toplam eleman sayısı
<br>**dtype:** array veri tipi

In [2]:
import numpy as np

In [5]:
# 0 ile 10 aralığında 10 elemalı numpy array oluşturur

np.random.randint(10, size = 10)

array([6, 5, 1, 8, 1, 0, 4, 3, 6, 6])

In [6]:
# bu şekilde olursa sadece 0 ile 10 değerleri aralığında 1 adet değer üretecektir

np.random.randint(10)

4

In [7]:
a = np.random.randint(10, size = 10)

In [8]:
# boyut sayısı hakkında bilgi almak

a.ndim

1

In [9]:
# a değişkenine atanmış array tek boyutlu olduğu için sadece tek boyut hakkında bilgi verir
# içerisinde ka. adet eleman olduğunu belirtir

a.shape

(10,)

In [12]:
# numpy array içerisindeki toplam eleman sayısı
# iki boyutlu bir array üzeründe kullanacak olsaydık tüm barray üzerindeki elelmaların sayısı hakkında bilgi verecektir

a.size

10

In [13]:
# numpy array veri tipi bilgisi verir

a.dtype

dtype('int32')

___

## Reshaping (Yeniden Şekillendirme)

In [15]:
a = np.arange(1, 11)

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# reshape kullanrak 10 elemanlı ve tek boyutlu olan numpy array 2 satır, 5 sütun oluşan bir numpy array haline gelir 
# 2 * 5 = 10 değeri olduğu için dönüştürmeye çalıştığımız numpy array' in eleman sayısı bu değer ile aynı olmalıdır

a.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

tek boyutlu array **"vektör"** adı verilir.
<br> iki boyutlu array **"matris"** adı verilir.

____

## Concantenation (Birleştirme)

In [20]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [21]:
# yularıdaki x ve y numpy arrayler yan yana birleştirilir

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [22]:
z = np.array([7, 8, 9])

In [23]:
np.concatenate([x, y, x])

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [24]:
# birleştirme işlemi matrisler (iki boyutlu array) üzerinde de yapılabilir.

a = np.array([[1,2,3],
              [4,5,6]])

np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
# axis paremetresi ile satır veya sütun bazında birleştirme yapılabilmektedir.
# 0 değeri satır, 1 değeri ise sütun anlamına gelir
# eğer axis paremetresi çağırılmazsa "concatenate()" varsayılan olarak axis = 0 değeri kullanır

np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
# sütun bazında birleştirme

np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

____

## Splitting (Ayırma)

In [27]:
x = np.array([1,2,3,99,99,3,2,1])

In [29]:
np.split(x, [3, 5])

# x değerine atamış olduğumuz numpy array içerinden ilk 3 elemanı 
# daha sonra 5'e kadar olan ksımı (ilk 3 eleman hariç, çünkü ilk olarak alınmışlardır) 
# ve son olarak geriye kalan elemaları alır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [30]:
# almış olduğumuz 3 farklı çıktıyı, 3 farklı değişkene atanabilir

a, b, c = np.split(x, [3, 5])

In [32]:
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


In [33]:
# matrislerde split (ayırma) işlemi

In [34]:
# 16 elemanlı bir array oşuşturulur ve 4 satır, 4 sütundan oluşan matris haline geitirlir
# arange ve reshape tek satırda kullanımı

m = np.arange(16).reshape(4,4)

m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
# m değişkenine atanmış matrisi ikiye bölme işlemi

np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [36]:
# iki çıktıyı, iki farklı değişkene atama işlemi

ust, alt = np.vsplit(m, [2])

In [37]:
print(ust)
print(alt)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
# ancak bu işlem satır bazında yapılmıştır

In [39]:
# hsplit ile sütun bazında da yapılabilir

np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [40]:
sag, sol = np.hsplit(m, [2])

In [41]:
print(sag)
print(sol)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


___

## Sorting (Sıralama)

In [42]:
z = np.array([2,1,4,3,5])
z

array([2, 1, 4, 3, 5])

In [43]:
# bu şekilde z değişkenine atanmış olan numpy array elemanları sıralama işlemine tabi tutulur

np.sort(z)

array([1, 2, 3, 4, 5])

In [44]:
# z.sort() şeklinde kullanımıda vardır ancak bu verimiz üzerinde kalıcı değişiklik yapmaktadır
# ancak ana veri seti üzerinde kalıcı değişiklik yapmak istiyeciğimiz bir durum değildir.

In [47]:
# matrisler üzerinde sort (sıralama) işlemi

In [48]:
# oratlaması 20, standar sapması 5 olan bir martis oluşturmak

m = np.random.normal(20,5, (3,3))
m

array([[18.78984714, 18.08519457, 18.52344768],
       [22.02783243, 10.29144108, 22.56044484],
       [22.31738579,  9.06751796, 21.47678171]])

In [49]:
np.sort(m)

array([[18.08519457, 18.52344768, 18.78984714],
       [10.29144108, 22.02783243, 22.56044484],
       [ 9.06751796, 21.47678171, 22.31738579]])

In [50]:
# yukarıda görüldüğü gibi satırları kendi içerisinde sıralama işlemi yapmıştır

In [51]:
np.sort(m, axis = 1)
# sütunları kendi içerinde sıralar

array([[18.08519457, 18.52344768, 18.78984714],
       [10.29144108, 22.02783243, 22.56044484],
       [ 9.06751796, 21.47678171, 22.31738579]])

In [52]:
np.sort(m, axis = 0)
# satırları kendi içerisnde sıralar

array([[18.78984714,  9.06751796, 18.52344768],
       [22.02783243, 10.29144108, 21.47678171],
       [22.31738579, 18.08519457, 22.56044484]])