## Numpy Nedir?

Numpy, Numerical Python kelimelerinden ismini alan Python programlama dili kütüphanesidir. Numpy kütüphanesi ile Çok boyutlu diziler ve matrisler ile çalışıp, matematiksel işlemler yapabilirisiniz. Bu yaptığınız işlemler Python dili içerisinde bulunan liste yapılarına ve matematiksel işlemlere göre çok daha verimli ve hızlı bir şekilde gerçekleşmesine olanak sağlar.
<br><br>
Python dili içerisinde bulunan liste yapılarından daha verimli bir şekilde kullanabileceğimiz, Çok boyutlu diziler, matrisler ile çalışmamıza ve matematiksel işlemleri çok hızlı bir biçimde yapabilmemize olanak sağlar.

In [1]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

Aynı işlemlerin numpy ile yapılışı...

In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

In [6]:
a*b

array([ 2,  6, 12, 20])

In [7]:
b = a*b
type(b)

numpy.ndarray

In [10]:
# numpy içerisinde tek tip veri kaydeder

np.array([4.14, 2, 3, 5])

# 4.14 değişkeni ondalıklı olduğu için tüm değerler float olarka tutulur

array([4.14, 2.  , 3.  , 5.  ])

In [11]:
# numpy arrayleri oluşturulurken veri tipi belirtilebilir

np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [13]:
# sıfırlardan array oluşturmak

np.zeros(5)

# bu şekilde değerleir sıfır olan 5 elemanlı bir numpy array oluşturulabilir

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5, dtype="int")

array([1, 1, 1, 1, 1])

In [18]:
# iki boyutlu numpy array oluşturmak (3 satır, 5 sütun)

np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# 3 değerindne oluşan 3 satırlı ve 5 sütunlu numpy array

np.full((3, 5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [21]:
# 3'er atlayark 0' dan 30' a kadar olan değerler ile numpy array oluşturu

np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [23]:
# 0 ile 1 değer aralığını 5 eşit parçaya böler

np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# ortalaması 10, standart sapması 4 olan 3 sütuna ve 4 satıra sahip numpy array oluşturu

np.random.normal(10, 4, (3, 4))

array([[12.91453864,  7.46274508, 12.414291  , 16.39896774],
       [17.22062739,  7.6181949 , 10.06881858,  7.1276192 ],
       [ 8.46027498,  9.56695   , 17.16736548,  9.20590683]])

In [25]:
# 0 ile 10 değerleri aralığında 3 sütuna ve 3 satıra sahip numpy array oluşturur

np.random.randint(0, 10, (3,3))

array([[4, 0, 7],
       [6, 2, 1],
       [8, 0, 2]])