## Matematiksel İşlemler

In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [3]:
print(v - 1)
print(v * 5)
print(v / 5)

[0 1 2 3 4]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]


In [4]:
# v - 1 ile aynı sonucu verecektir

np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [8]:
# v + 1 

np.add(v, 1)

array([2, 3, 4, 5, 6])

In [9]:
# v * 4

np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [10]:
# v / 5

np.divide(v, 5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [11]:
# v ** 3

np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
# v % 2

np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
# mutlak değer

np.absolute(np.array([-3, 2, -5]))

array([3, 2, 5])

In [14]:
# sinüs

np.sin(360)

0.9589157234143065

In [15]:
# kosinüs

np.cos(180)

-0.5984600690578581

In [16]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [17]:
# logaritma

np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [18]:
# taban 2 

np.log2(v)

array([0.       , 1.       , 1.5849625])

In [19]:
# taban 10

np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [21]:
v

array([1, 2, 3])

In [22]:
# ortalama

np.mean(v)

2.0

In [23]:
# minumum değer

v.min()

1

In [24]:
# maksimum değer

v.max()

3

In [25]:
# elemanların toplamı

v.sum()

6

**?np** ifadesini input katmanına koyarak çalıştırarak numpy' ın dökümanına ulaşabilirsiniz.